---
- name: Mini0 | Disk | Unencrypted | Install cryptsetup
  ansible.builtin.package:
      name: cryptsetup
      state: present

- name: Mini0 | Disk | Unencrypted | Copy key file
  ansible.builtin.copy:
      content: "{{ cs_mini0_external_disk_enc_key_base64 | b64decode }}"
      dest: /root/.minio-luks-key
      mode: "0000"
      remote_src: false

- name: Mini0 | Disk | Unencrypted | Create mount point
  ansible.builtin.file:
      path: "{{ cs_mini0_external_disk_mount_path }}"
      state: directory
      mode: "0755"

- name: Mini0 | Disk | Unencrypted | Add luks key
  community.crypto.luks_device:
      state: opened
      name: "{{ cs_mini0_external_disk_crypt_open_name }}"
      uuid: "{{ cs_mini0_external_disk_uuid }}"
      # keyfile: /root/.minio-luks-key
      passphrase: "{{ cs_mini0_external_disk_enc_password }}"
      new_keyfile: /root/.minio-luks-key

- name: Mini0 | Disk | Unencrypted | Add to crypttab
  ansible.builtin.lineinfile:
      path: /etc/crypttab
      line: "{{ cs_mini0_external_disk_crypt_open_name }} UUID={{ cs_mini0_external_disk_uuid }}
          /root/.nfs-luks-key luks"
      create: true
      mode: "0644"
      owner: root
      group: root
      regexp: "^{{ cs_mini0_external_disk_crypt_open_name }}"

- name: Mini0 | Disk | Unencrypted | Remove from fstab
  ansible.builtin.lineinfile:
      path: /etc/fstab
      regexp: "^/dev/mapper/{{ cs_mini0_external_disk_crypt_open_name }}.*"
      state: absent

- name: Mini0 | Disk | Unencrypted | Mount
  ansible.posix.mount:
      src: /dev/mapper/{{ cs_mini0_external_disk_crypt_open_name }}
      path: "{{ cs_mini0_external_disk_mount_path }}"
      fstype: ext4
      state: mounted
      boot: true
      opts: defaults,noatime,nofail
      dump: 0
      passno: 2

- name: Mini0 | Disk | Unencrypted | Perform systemd daemon-reload
  ansible.builtin.systemd_service:
      daemon_reload: true

- name: "Mini0 | Disk | Unencrypted | Check for self uuid file
      {{ cs_mini0_external_disk_mount_path + '/' + cs_mini0_external_disk_uuid }}"
  ansible.builtin.stat:
      path: "{{ cs_mini0_external_disk_mount_path }}/{{ cs_mini0_external_disk_uuid }}"
  register: uuid_file
  failed_when: not uuid_file.stat.exists
