---
all:
    vars:
        cs_env_debug: "{{ lookup('ansible.builtin.env', 'DEBUG', default=false) | bool }}"
        cs_no_log: "{{ not cs_env_debug }}"
        # ansible_user: "{{ cs_vm_ssh_service_user_id }}"
        # ansible_ssh_private_key_file: "{{ cs_vm_ssh_local_key_file }}"

    children:
        patchservers:
            hosts:
                rb4-m1:
                rb4-m2:
                rb4-m3:
    hosts:
        localhost:
        rb4-m1:
            ansible_host: "{{ cs_rb4_m1_ip }}"
            # ansible_user: root
            # ansible_ssh_password: password
            # ansible_become_method: su
            # ansible_become_password: root
        rb4-m2:
            ansible_host: "{{ cs_rb4_m2_ip }}"
        rb4-m3:
            ansible_host: "{{ cs_rb4_m3_ip }}"
