---
- name: Access Key
  hosts: localhost
  become: false
  gather_facts: false
  no_log: "{{ cs_no_log }}"
  tags: always
  tasks:
      - name: Access Key | Write SSH Private Key
        ansible.builtin.copy:
            content: "{{ cs_vm_ssh_priv_id_ecdsa_b64 | b64decode
                | get_unencrypted_id_ecdsa(password=cs_vm_ssh_priv_id_ecdsa_password) }}"
            mode: "0600"
            dest: "{{ cs_vm_ssh_local_key_file }}"

- name: Mini0
  hosts: localhost
  become: false
  gather_facts: false
  no_log: "{{ cs_no_log }}"
  tags: never,mini0
  tasks:
      - name: Get BWS Secret
        ansible.builtin.import_tasks:
            file: tasks/secrets.yml
      - name: Mini0
        ansible.builtin.import_tasks:
            file: tasks/minio.yml

- name: Nextcloud
  hosts: nextcloud-aio
  become: true
  become_user: root
  gather_facts: true
  no_log: "{{ cs_no_log }}"
  tasks:
      - name: Patch Cloud System
        tags: never,nextcloud,nextcloud_patch
        ansible.builtin.import_tasks:
            file: tasks/patch.yml

      - name: Nextcloud | Prepare
        tags: never,nextcloud,nextcloud_prepare
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00000-prepare.yml

      - name: Nextcloud | Database
        tags: never,nextcloud,nextcloud_database
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00100-db.yml

      - name: Nextcloud | Install
        tags: never,nextcloud,nextcloud_install
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00200-install.yml

      - name: Nextcloud | Admin
        tags: never,nextcloud,nextcloud_admin
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00300-admin.yml

      - name: Nextcloud | Cache
        tags: never,nextcloud,nextcloud_cache
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00400-cache.yml

      - name: Nextcloud | Imaginary
        tags: never,nextcloud,nextcloud_imaginary
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00500-imaginary.yml

      - name: Nextcloud | Full Text Search
        tags: never,nextcloud,nextcloud_fulltextsearch
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/00600-fulltextsearch.yml

      - name: Nextcloud | Post Install
        tags: never,nextcloud,nextcloud_post_install,nextcloud_install
        ansible.builtin.import_tasks:
            file: tasks/nextcloud/99999-post-install.yml
