[tool.poetry]
name = "certificate-authority"
version = "0.1.0"
description = ""
authors = ["arpan <arpan.rec@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^10.0.0"
jmespath = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pylint = "^3.2.2"
ansible-lint = { version = "^24.6.0", markers = 'platform_system != "Windows"' }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
