---
collections:
    - name: community.general
      version: 9.1.0
    - name: community.crypto
      version: 2.20.0
    - name: community.docker
      version: 3.10.4
    - name: ansible.posix
      version: 1.5.2
    - name: bitwarden.secrets
      version: 1.0.0
    - name: linode.cloud
      version: 0.27.0
    - name: arpanrec.nebula
      source: https://github.com/arpanrec/arpanrec.nebula.git
      type: git
    - name: viczem.keepass
      source: https://github.com/viczem/ansible-keepass.git
      version: v0.7.5
      type: git
roles:
    - name: geerlingguy.docker
      version: 7.1.0
