---
- name: Database | Elasticsearch | Stop old dependency containers
  community.docker.docker_container:
      name: elasticsearch-main
      state: absent
      force_kill: true

- name: Database | Elasticsearch | Get Service user details
  ansible.builtin.getent:
      database: passwd
      key: "{{ cs_vm_ssh_service_user_id }}"

- name: Database | Elasticsearch | Create elasticsearch Data Directory
  ansible.builtin.file:
      path: "{{ cs_elasticsearch_data_dir }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_vm_ssh_service_user_id }}"

- name: Database | Elasticsearch | Create elasticsearch Container
  community.docker.docker_container:
      name: elasticsearch-main
      image: "docker.io/nextcloud/aio-fulltextsearch:latest"
      user: "{{ getent_passwd[cs_vm_ssh_service_user_id].1 }}"
      volumes:
          - "{{ cs_elasticsearch_data_dir }}:/usr/share/elasticsearch/data:rw"
      ports:
          - "{{ cs_elasticsearch_servlet_port }}:{{ cs_elasticsearch_servlet_port }}"
          - "{{ cs_elasticsearch_transport_port }}:9300"
      state: started
      restart_policy: unless-stopped
      env:
          TZ: Asia/Kolkata
          "discovery.type": "single-node"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          "node.name": "es01"
          "cluster.name": docker-cluster
          "bootstrap.memory_lock": "true"
          "http.port": "{{ cs_elasticsearch_servlet_port | string }}"
          "xpack.license.self_generated.type": basic
          "xpack.security.enabled": "false"
          "logger.org.elasticsearch.discovery": WARN
          ELASTIC_CONTAINER: "true"
          FULLTEXTSEARCH_PASSWORD: "{{ cs_elasticsearch_password }}"
      ulimits:
          - "memlock:-1:-1"

- name: Database | Elasticsearch | Enable UFW port
  community.general.ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
  with_items:
      - "{{ cs_elasticsearch_servlet_port }}"
      - "{{ cs_elasticsearch_transport_port }}"

- name: Database | Elasticsearch | Wait for elasticsearch to start
  ansible.builtin.uri:
      url: "http://elastic:{{ cs_elasticsearch_password }}@{{ cs_elasticsearch_host }}:{{
          cs_elasticsearch_servlet_port }}"
      method: GET
      status_code: [200]
      timeout: 3
      return_content: true
  register: cs_nc_fulltextsearch_status
  until: cs_nc_fulltextsearch_status.status == 200
  retries: 30
  delay: 3
