---
- name: Linode | add id_ed25519 to user account
  linode.cloud.ssh_key:
      label: "{{ sdic_linode_id_ed25519_key_label }}"
      state: present
      ssh_key: "{{ sdic_linode_id_ed25519_pub }}"
      api_token: "{{ linode_api_token }}"

- name: Linode | Add SDIC to Linode Cloud DNS
  linode.cloud.domain:
      domain: "{{ sdic_linode_manage_domain }}"
      type: master
      state: present
      api_token: "{{ linode_api_token }}"
      status: active
      soa_email: "{{ linode_email_id }}"
      refresh_sec: 300
      retry_sec: 300
      ttl_sec: 300

- name: Linode | Get the Linode Domain Info
  linode.cloud.domain_info:
      domain: "{{ sdic_linode_manage_domain }}"
      api_token: "{{ linode_api_token }}"
  register: linode_domain_info


# - name: Linode | Make Godaddy NS Record for Linode Domain
#   ansible.builtin.uri:
#       url: "https://api.godaddy.com/v1/domains/{{ sdic_godaddy_master_domain }}/records/NS/\
#           {{ sdic_linode_manage_sub_domain_name }}"
#       method: PUT
#       headers:
#           Authorization: "sso-key {{ sdic_godaddy_api_key }}:{{ sdic_godaddy_api_secret }}"
#       body_format: json
#       body:
#           - { "data": "ns1.linode.com", "name": "sdic", "ttl": 600, "type": "NS" }
#           - { "data": "ns2.linode.com", "name": "sdic", "ttl": 600, "type": "NS" }
#           - { "data": "ns3.linode.com", "name": "sdic", "ttl": 600, "type": "NS" }
#           - { "data": "ns4.linode.com", "name": "sdic", "ttl": 600, "type": "NS" }
#           - { "data": "ns5.linode.com", "name": "sdic", "ttl": 600, "type": "NS" }
