---
- name: Mini0 | Linode
  ansible.builtin.import_tasks:
      file: tasks/minio/linode.yml

- name: Mini0 | Add to inv
  ansible.builtin.import_tasks:
      file: tasks/minio/add_inv.yml

- name: Mini0 | Patch Cloud System
  delegate_to: cs-minio-linode-host
  ansible.builtin.import_tasks: tasks/minio/patch.yml

- name: Mini0 | Reboot Mini0 Instance
  block:
      - name: Mini0 | Reboot Mini0 Instance | Reboot
        linode.cloud.instance:
            api_token: "{{ linode_api_token }}"
            label: "{{ minio_linode_instance_label }}"
            state: present
            rebooted: true

      - name: Mini0 | Reset inventory host host entry
        ansible.builtin.add_host:
            hostname: cs-minio-linode-host
            ansible_ssh_host: "{{ minio_linode_instance_info.networking.ipv4.public[0].address }}"
            ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
            ansible_user: "{{ linode_vm_ssh_service_user }}"
            ansible_connection: ssh
            ansible_become_method: sudo
            ansible_ssh_private_key_file: "{{ ssh_key_file_temp.path }}"

      - name: Mini0 | Reboot Mini0 Instance | Wait
        delegate_to: cs-minio-linode-host
        ansible.builtin.wait_for_connection:
            delay: 1
            timeout: 1
        retries: 30
        delay: 3

- name: Mini0 | Disk
  delegate_to: cs-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/disk.yml

- name: Mini0 | KES
  delegate_to: cs-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/kes.yml

- name: Mini0 | Mini0
  delegate_to: cs-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/server.yml

- name: Mini0 | Health Check
  ansible.builtin.uri:
      url: "https://{{ minio_server_domain }}:{{ minio_server_port }}/minio/health/live"
      method: GET
      status_code: [200]
      return_content: false
      validate_certs: true
