---
- name: NFS Client | Install NFS client | Install nfs-common
  ansible.builtin.package:
      name: nfs-common
      state: present

- name: NFS Client | Mount NFS share | Create mount point
  ansible.builtin.file:
      path: "{{ cs_nfs_external_drive_mount_path }}"
      state: directory
      mode: "0755"

- name: NFS Client | Mount NFS share | Mount
  timeout: 10
  ansible.posix.mount:
      src: "{{ cs_nfs_server_ip }}:{{ cs_nfs_external_drive_mount_path }}"
      path: "{{ cs_nfs_external_drive_mount_path }}"
      fstype: nfs
      state: mounted
      boot: true
