---
- name: Nextcloud | Cache | Set nextcloud config
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  with_items:
      - "config:system:set redis host --value {{ cs_nc_redis_host }}"
      - "config:system:set redis port --value {{ cs_nc_redis_port }}"
      - "config:system:set redis timeout --value {{ cs_nc_redis_timeout }}"
      - "config:system:set redis password --value {{ cs_nc_redis_password }}"

      - "config:system:set memcache.local --value '\\OC\\Memcache\\APCu'"
      - "config:system:set memcache.distributed --value '\\OC\\Memcache\\Redis'"
      - "config:system:set memcache.locking --value '\\OC\\Memcache\\Redis'"
