---
- name: Nextcloud | Data Dump | Directory
  ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"
  with_items:
      - "{{ cs_nc_external_drive_mount_data_dump_path }}"
      - "{{ cs_nc_external_drive_mount_data_dump_path }}/current"

- name: Nextcloud | Data Dump | Install rsync
  ansible.builtin.apt:
      name:
          - rsync
          - zstd
      state: present

- name: Nextcloud | Data Dump | Create Script
  ansible.builtin.template:
      mode: "0755"
      dest: "{{ cs_nc_root_dir }}/create_dump.sh"
      src: "templates/nc/create_dump.sh.j2"

- name: Nextcloud | Data Dump | Create systemd service
  ansible.builtin.template:
      mode: "0644"
      dest: "/etc/systemd/system/nextcloud-data-dump.service"
      src: "templates/nc/nextcloud-data-dump.service.j2"

- name: Nextcloud | Data Dump | Create systemd timer
  ansible.builtin.copy:
      mode: "0644"
      dest: "/etc/systemd/system/nextcloud-data-dump.timer"
      src: files/nc/nextcloud-data-dump.timer
      remote_src: false

- name: Nextcloud | Data Dump | Make sure cron systemd service is enabled
  ansible.builtin.systemd:
      name: nextcloud-data-dump.timer
      enabled: true
      state: started
      daemon_reload: true
