---
- name: Nextcloud | Full Text Search | Stop old dependency containers
  community.docker.docker_container:
      name: "nextcloud-fulltextsearch"
      state: absent
      force_kill: true

- name: Nextcloud | Full Text Search | Get Service user details
  ansible.builtin.getent:
      database: passwd
      key: "{{ cs_vm_ssh_service_user_id }}"
  register: cs_nc_service_user

- name: Nextcloud | Full Text Search | Create fulltextsearch Data Directory
  ansible.builtin.file:
      path: "{{ cs_nc_fulltextsearch_data_dir }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_vm_ssh_service_user_id }}"

- name: Nextcloud | Full Text Search | Create network
  community.docker.docker_network:
      name: nextcloud
      state: present

- name: Nextcloud | Full Text Search | Create fulltextsearch Container
  community.docker.docker_container:
      name: nextcloud-fulltextsearch
      image: "docker.io/nextcloud/aio-fulltextsearch:latest"
      user: "{{ getent_passwd[cs_vm_ssh_service_user_id].1 }}"
      networks:
          - name: nextcloud
      volumes:
          - "{{ cs_nc_fulltextsearch_data_dir }}:/usr/share/elasticsearch/data:rw"
      ports:
          - "9200:9200"
          - "9300:9300"
      state: started
      restart_policy: always
      env:
          TZ: Asia/Kolkata
          "discovery.type": "single-node"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
          "node.name": "es01"
          "cluster.name": docker-cluster
          "bootstrap.memory_lock": "true"
          "http.port": "9200"
          "xpack.license.self_generated.type": basic
          "xpack.security.enabled": "false"
          "logger.org.elasticsearch.discovery": WARN
          ELASTIC_CONTAINER: "true"
          FULLTEXTSEARCH_PASSWORD: "{{ cs_nc_fulltextsearch_password }}"
      ulimits:
          - "memlock:-1:-1"

- name: Nextcloud | Full Text Search | Wait for fulltextsearch to start
  ansible.builtin.uri:
      url: "http://elastic:{{ cs_nc_fulltextsearch_password }}@127.0.0.1:9200"
      method: GET
      status_code: [200]
      timeout: 3
      return_content: true
  register: cs_nc_fulltextsearch_status
  until: cs_nc_fulltextsearch_status.status == 200
  retries: 30
  delay: 3

- name: Nextcloud | Full Text Search | List all apps
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ app:list --output=json"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: false
  register: cs_nc_app_list

- name: Nextcloud | Full Text Search | Install apps
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ app:install {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  with_items:
      - "fulltextsearch"
      - "files_fulltextsearch"
      - "fulltextsearch_elasticsearch"
  when: >
      not
      (
        item in cs_nc_app_list.stdout | from_json | json_query('enabled')
      or
        item in cs_nc_app_list.stdout | from_json | json_query('disabled')
      )

- name: Nextcloud | Full Text Search | create nextcloud-fulltext-elasticsearch-worker
  ansible.builtin.copy:
      dest: /etc/systemd/system/nextcloud-fulltext-elasticsearch-worker.service
      content: |+
          [Unit]
          Description=Elasticsearch Worker for Nextcloud Fulltext Search
          After=network.target

          [Service]
          User=www-data
          Group=www-data
          Type=simple
          WorkingDirectory={{ cs_nc_web_root_dir }}
          ExecStartPre=/usr/bin/php {{ cs_nc_web_root_dir }}/occ fulltextsearch:index
          ExecStart=/usr/bin/php {{ cs_nc_web_root_dir }}/occ fulltextsearch:live -q
          ExecStop=/usr/bin/php {{ cs_nc_web_root_dir }}/occ fulltextsearch:stop
          Nice=19
          Restart=always

          [Install]
          WantedBy=multi-user.target
      mode: "0644"

- name: Nextcloud | Full Text Search | Set Apps Config
  ansible.builtin.set_fact:
      cs_nc_app_config:
          apps:
              fulltextsearch:
                  "app_navigation": "1"
                  enabled: "yes"
                  search_platform: "OCA\\FullTextSearch_Elasticsearch\\Platform\\ElasticSearchPlatform"
                  "types": ""
              fulltextsearch_elasticsearch:
                  enabled: "yes"
                  elastic_host: "http://elastic:{{ cs_nc_fulltextsearch_password }}@127.0.0.1:9200"
                  elastic_index: "nextcloud"
                  elastic_type: "file"
                  analyzer_tokenizer: "standard"
                  types: ""
              files_fulltextsearch:
                  enabled: "yes"
                  types: "filesystem"
                  files_local: "1"
                  files_size: "20"
                  files_pdf: "1"
                  files_office: "1"
                  files_image: "0"
                  files_audio: "0"
                  files_group_folders: "1"
                  files_external: "1"

- name: Nextcloud | Full Text Search | Write Apps Config
  ansible.builtin.copy:
      content: "{{ cs_nc_app_config | to_nice_json }}"
      dest: "/tmp/nc-apps-config.json"
      mode: "0644"

- name: Nextcloud | Full Text Search | Import Apps Config
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ config:import /tmp/nc-apps-config.json"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true

- name: Nextcloud | Full Text Search | Stop nextcloud-fulltext-elasticsearch-worker
  ansible.builtin.systemd_service:
      name: nextcloud-fulltext-elasticsearch-worker.service
      enabled: false
      state: stopped
      daemon_reload: true

- name: Nextcloud | Full Text Search | Stop fulltextsearch
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ fulltextsearch:stop"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true

- name: Nextcloud | Full Text Search | Start nextcloud-fulltext-elasticsearch-worker
  ansible.builtin.systemd_service:
      name: nextcloud-fulltext-elasticsearch-worker.service
      enabled: true
      state: started
      daemon_reload: true
