---
- name: Nextcloud | Imaginary | Stop old dependency containers
  community.docker.docker_container:
      name: "nextcloud-imaginary"
      state: absent
      force_kill: true

- name: Nextcloud | Imaginary | Run Imaginary
  community.docker.docker_container:
      name: nextcloud-imaginary
      image: "docker.io/nextcloud/aio-imaginary:latest"
      state: started
      restart_policy: always
      ports:
          - "9000:9000"
      env:
          TZ: "Asia/Kolkata"
          IMAGINARY_SECRET: "{{ cs_nc_imaginary_key }}"
          PORT: "9000"
      command: -enable-url-source

- name: Nextcloud | Imaginary | Set nextcloud config
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  with_items:
      # - "config:system:set enabledPreviewProviders 1 --value='OC\\Preview\\BMP'"
      # - "config:system:set enabledPreviewProviders 2 --value='OC\\Preview\\GIF'"
      # - "config:system:set enabledPreviewProviders 3 --value='OC\\Preview\\JPEG'"
      # - "config:system:set enabledPreviewProviders 4 --value='OC\\Preview\\PNG'"
      # - "config:system:set enabledPreviewProviders 5 --value='OC\\Preview\\SVG'"
      # - "config:system:set enabledPreviewProviders 6 --value='OC\\Preview\\HEIC'"
      # - "config:system:set enabledPreviewProviders 7 --value='OC\\Preview\\MP3'"
      # - "config:system:set enabledPreviewProviders 8 --value='OC\\Preview\\TXT'"
      # - "config:system:set enabledPreviewProviders 9 --value='OC\\Preview\\MarkDown'"
      # - "config:system:set enabledPreviewProviders 10 --value='OC\\Preview\\Movie'"
      # - "config:system:set enabledPreviewProviders 11 --value='OC\\Preview\\PDF'"
      # - "config:system:set enabledPreviewProviders 12 --value='OC\\Preview\\Photoshop'"
      # - "config:system:set enabledPreviewProviders 13 --value='OC\\Preview\\Illustrator'"
      # - "config:system:set enabledPreviewProviders 14 --value='OC\\Preview\\TIFF'"
      # - "config:system:set enabledPreviewProviders 15 --value='OC\\Preview\\XBitmap'"
      # - "config:system:set enabledPreviewProviders 16 --value='OC\\Preview\\XPM'"
      # - "config:system:set enabledPreviewProviders 17 --value='OC\\Preview\\XCF'"
      # - "config:system:set enabledPreviewProviders 18 --value='OC\\Preview\\MP4'"
      # - "config:system:set enabledPreviewProviders 19 --value='OC\\Preview\\AVI'"
      # - "config:system:set enabledPreviewProviders 20 --value='OC\\Preview\\MKV'"
      # - "config:system:set enabledPreviewProviders 21 --value='OC\\Preview\\WMV'"
      # - "config:system:set enabledPreviewProviders 22 --value='OC\\Preview\\FLV'"
      # - "config:system:set enabledPreviewProviders 23 --value='OC\\Preview\\MOV'"
      # - "config:system:set enabledPreviewProviders 24 --value='OC\\Preview\\WEBM'"
      # - "config:system:set enabledPreviewProviders 25 --value='OC\\Preview\\AVIF'"
      # - "config:system:set enabledPreviewProviders 26 --value='OC\\Preview\\WEBP'"
      # - "config:system:set enabledPreviewProviders 27 --value='OC\\Preview\\AVIF'"
      - "config:system:delete enabledPreviewProviders"
      - "config:system:set preview_imaginary_url --value 'http://127.0.0.1:9000'"
      - "config:system:set preview_imaginary_key --value '{{ cs_nc_imaginary_key }}'"
