---
- name: Nextcloud | Imaginary | Stop old dependency containers
  community.docker.docker_container:
      name: "nextcloud-imaginary"
      state: absent
      force_kill: true

- name: Nextcloud | Imaginary | Run Imaginary
  community.docker.docker_container:
      name: nextcloud-imaginary
      image: "docker.io/nextcloud/aio-imaginary:latest"
      state: started
      restart_policy: unless-stopped
      ports:
          - "{{ cs_nc_imaginary_port }}:{{ cs_nc_imaginary_port }}"
      env:
          TZ: "Asia/Kolkata"
          IMAGINARY_SECRET: "{{ cs_nc_imaginary_key }}"
          PORT: "{{ cs_nc_imaginary_port | string }}"
      command: -enable-url-source

- name: Nextcloud | Imaginary | Set Imaginary as Preview Provider
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  with_items:
      - "config:system:delete enabledPreviewProviders"
      - "config:system:set enabledPreviewProviders 0 --value='OC\\Preview\\Imaginary'"
      - "config:system:set enabledPreviewProviders 1 --value='OC\\Preview\\Image'"
      - "config:system:set enabledPreviewProviders 2 --value='OC\\Preview\\MarkDown'"
      - "config:system:set enabledPreviewProviders 3 --value='OC\\Preview\\MP3'"
      - "config:system:set enabledPreviewProviders 4 --value='OC\\Preview\\TXT'"
      - "config:system:set enabledPreviewProviders 5 --value='OC\\Preview\\OpenDocument'"
      - "config:system:set enabledPreviewProviders 6 --value='OC\\Preview\\Movie'"
      - "config:system:set enabledPreviewProviders 7 --value='OC\\Preview\\Krita'"
      - "config:system:set enable_previews --value true"
      - "config:system:set preview_imaginary_url --value 'http://{{ cs_nc_imaginary_domain }}:{{
        cs_nc_imaginary_port }}'"
      - "config:system:set preview_imaginary_key --value '{{ cs_nc_imaginary_key }}'"
      - "config:system:set preview_max_x --value 2048"
      - "config:system:set preview_max_y --value 2048"
      - "config:system:set jpeg_quality --value 60"
