---
- name: Nextcloud | Mount Disk | Set facts
  ansible.builtin.set_fact:
      cold_storage_disk_uuid: 029d8364-b165-4b7e-a7b3-5202f2a3e21a
      cold_storage_disk_mount_point: /mnt/coldstorage

- name: Nextcloud | Mount Disk | Set facts systemd service name
  ansible.builtin.set_fact:
      cold_storage_disk_systemd_service_name: "{{ cold_storage_disk_mount_point
          | regex_replace('^/', '') | regex_replace('/', '-') }}"

- name: Nextcloud | Mount Disk | Create mount point
  ansible.builtin.file:
      path: "{{ cold_storage_disk_mount_point }}"
      state: directory
      mode: "0755"

- name: Nextcloud | Mount Disk | Create systemd mount unit
  ansible.builtin.copy:
      content: |+
          [Unit]
          Description=Nextcloud Disk
          After=network.target
          SourcePath=/etc/fstab

          [Mount]
          What=/dev/disk/by-uuid/{{ cold_storage_disk_uuid }}
          Where={{ cold_storage_disk_mount_point }}
          Type=ext4
          Options=defaults,noatime,nofail

          [Install]
          WantedBy=multi-user.target
      dest: /etc/systemd/system/{{ cold_storage_disk_systemd_service_name }}.mount
      mode: "0644"

- name: Nextcloud | Mount Disk | Create systemd automount unit
  ansible.builtin.copy:
      content: |+
          [Unit]
          Description=Nextcloud Disk Automount
          After=network.target
          SourcePath=/etc/fstab

          [Automount]
          Where={{ cold_storage_disk_mount_point }}

          [Install]
          WantedBy=multi-user.target
      dest: /etc/systemd/system/{{ cold_storage_disk_systemd_service_name }}.automount
      mode: "0644"

- name: Nextcloud | Mount Disk | Enable systemd automount unit
  ansible.builtin.systemd:
      name: "{{ cold_storage_disk_systemd_service_name }}.automount"
      enabled: true
      state: started
      daemon_reload: true

- name: Nextcloud | Mount Disk | Enable systemd mount unit
  ansible.builtin.systemd:
      name: "{{ cold_storage_disk_systemd_service_name }}.mount"
      enabled: true
      state: started
      daemon_reload: true

- name: "Nextcloud | Mount Disk | Check for self uuid file
      {{ cold_storage_disk_mount_point + '/' + cold_storage_disk_uuid }}"
  ansible.builtin.stat:
      path: "{{ cold_storage_disk_mount_point }}/{{ cold_storage_disk_uuid }}"
  register: nextcloud_uuid_file
  failed_when: not nextcloud_uuid_file.stat.exists

- name: Nextcloud | Mount Disk | Create backup and ops directory
  ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      mode: "0755"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
  with_items:
      - path: "{{ cold_storage_disk_mount_point }}/backup"
        owner: www-data
        group: www-data
      - path: "{{ cold_storage_disk_mount_point }}/ops"
        owner: www-data
        group: www-data
      - path: "{{ cold_storage_disk_mount_point }}/nextcloud"
        owner: www-data
        group: www-data
