---
- name: Nextcloud | Mount Disk | Install cryptsetup
  ansible.builtin.package:
      name: cryptsetup
      state: present

- name: Nextcloud | Mount Disk | Copy key file
  ansible.builtin.copy:
      content: "{{ cs_nc_external_drive_luks_key_file_b64 | b64decode }}"
      dest: /root/.nextcloud-luks-key
      mode: "0000"

- name: Nextcloud | Mount Disk | Create mount point
  ansible.builtin.file:
      path: "{{ cs_nc_external_drive_mount_path }}"
      state: directory
      mode: "0755"

- name: Nextcloud | Mount Disk | Add luks key
  community.crypto.luks_device:
      state: opened
      name: nextcloud
      uuid: "{{ cs_nc_external_drive_uuid }}"
      # keyfile: /root/.nextcloud-luks-key
      passphrase: "{{ cs_nc_external_drive_luks_password }}"
      new_keyfile: /root/.nextcloud-luks-key

- name: Nextcloud | Mount Disk | Add to crypttab
  ansible.builtin.lineinfile:
      path: /etc/crypttab
      line: "nextcloud UUID={{ cs_nc_external_drive_uuid }} /root/.nextcloud-luks-key luks"
      create: true
      mode: "0644"
      owner: root
      group: root
      regexp: "^nextcloud"

- name: Nextcloud | Mount Disk | Mount
  ansible.posix.mount:
      src: /dev/mapper/nextcloud
      path: "{{ cs_nc_external_drive_mount_path }}"
      fstype: ext4
      state: mounted
      boot: true
      opts: defaults,noatime,nofail
      dump: 0
      passno: 2

- name: Nextcloud | Mount Disk | Perform systemd daemon-reload
  ansible.builtin.systemd_service:
      daemon_reload: true

- name: "Nextcloud | Mount Disk | Check for self uuid file
      {{ cs_nc_external_drive_mount_path + '/' + cs_nc_external_drive_uuid }}"
  ansible.builtin.stat:
      path: "{{ cs_nc_external_drive_mount_path }}/{{ cs_nc_external_drive_uuid }}"
  register: nextcloud_uuid_file
  failed_when: not nextcloud_uuid_file.stat.exists

- name: Nextcloud | Mount Disk | Create backup and ops directory
  ansible.builtin.file:
      path: "{{ item.path }}"
      state: directory
      mode: "0755"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
  with_items:
      - path: "{{ cs_nc_external_drive_mount_path }}/backup"
        owner: www-data
        group: www-data
      - path: "{{ cs_nc_external_drive_mount_path }}/ops"
        owner: www-data
        group: www-data
      - path: "{{ cs_nc_external_drive_mount_path }}/nextcloud"
        owner: www-data
        group: www-data
