---
- name: Nextcloud | Hub Bundle | Set Apps Config
  ansible.builtin.set_fact:
      cs_nc_app_config:
          apps:
              onlyoffice:
                  # yamllint disable
                  "verify_peer_off": "false"
                  "DocumentServerUrl": "https://{{ cs_nc_domain }}:{{ cs_onlyoffice_port }}/"
                  "DocumentServerInternalUrl": "https://localhost:{{ cs_onlyoffice_port }}/"
                  "jwt_secret": "{{ cs_onlyoffice_jwt_secret }}"
                  "customization_plugins": "true"
                  "types": "prevent_group_restriction"
                  "customization_macros": "true"
                  "protection": "owner"
                  "defFormats": '{"doc":"false","docm":"false","docx":"true","dot":"false","dotm":"false","dotx":"false","epub":"false","fb2":"false","fodt":"false","htm":"false","html":"false","mht":"false","mhtml":"false","odt":"false","ott":"false","rtf":"false","stw":"false","sxw":"false","txt":"false","wps":"false","xml":"false","csv":"false","fods":"false","ods":"false","ots":"false","sxc":"false","xls":"false","xlsb":"false","xlsm":"false","xlsx":"true","xlt":"false","xltm":"false","xltx":"false","fodp":"false","odp":"false","otp":"false","pot":"false","potm":"false","potx":"false","pps":"false","ppsm":"false","ppsx":"false","ppt":"false","pptm":"false","pptx":"true","sxi":"false","pdf":"true","djvu":"false","docxf":"true","oform":"true","oxps":"false","xps":"false"}'
                  "editFormats": '{"epub":"false","fb2":"false","html":"false","odt":"false","ott":"false","rtf":"false","txt":"true","csv":"true","ods":"false","ots":"false","odp":"false","otp":"false"}'
                  "sameTab": "true"
                  "preview": "true"
                  "advanced": "false"
                  "cronChecker": "true"
                  "versionHistory": "true"
                  "groups": "[]"
                  "customizationChat": "true"
                  "customizationCompactHeader": "true"
                  "customizationFeedback": "true"
                  "customizationForcesave": "false"
                  "customizationHelp": "true"
                  "customizationToolbarNoTabs": "true"
                  "customizationReviewDisplay": "original"
                  "customizationTheme": "theme-classic-light"

- name: Nextcloud | Hub Bundle | Write
  ansible.builtin.copy:
      content: "{{ cs_nc_app_config | to_nice_json }}"
      dest: "/tmp/nc-apps-config.json"
      mode: "0644"

- name: Nextcloud | Hub Bundle | Import Apps Config
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ config:import /tmp/nc-apps-config.json"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
