---
- name: Nextcloud | Post Install | Enable required systemd services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
      state: restarted
      daemon_reload: true
  with_items:
      - apache2
      - php{{ cs_nc_php_version }}-fpm

- name: Nextcloud | Post Install | Enable UFW port
  community.general.ufw:
      rule: allow
      port: "{{ cs_nc_port }}"
      state: enabled

- name: Nextcloud | Post Install | Create log directory
  ansible.builtin.file:
      path: "{{ cs_nc_fail2ban_log_file | dirname }}"
      state: directory
      mode: "0755"
      owner: www-data
      group: www-data

- name: Nextcloud | Post Install | Touch log file
  ansible.builtin.file:
      path: "{{ cs_nc_fail2ban_log_file }}"
      state: touch
      mode: "0777"
      owner: www-data
      group: www-data

- name: Nextcloud | Post Install | Add fail2ban filter
  ansible.builtin.copy:
      mode: "0644"
      dest: /etc/fail2ban/filter.d/nextcloud.conf
      src: files/jail2ban.filter.conf

- name: Nextcloud | Post Install | Add fail2ban config
  ansible.builtin.template:
      mode: "0644"
      dest: /etc/fail2ban/jail.d/nextcloud.conf
      src: templates/jail2ban.conf.j2

- name: Nextcloud | Post Install | Restart fail2ban
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
      state: restarted
  with_items:
      - fail2ban
      - sendmail
