---
- name: Nextcloud | Post Install | Enable required systemd services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
      state: restarted
      daemon_reload: true
  with_items:
      - apache2
      - php{{ cs_nc_php_version }}-fpm

- name: Nextcloud | Post Install | Get Status
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ status --output=json"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: false
  register: nc_status

- name: Nextcloud | Post Install | Test if Nextcloud is installed correctly
  ansible.builtin.assert:
      that:
          - nc_current_status.installed
          - nc_current_status.versionstring == cs_nc_version
          - not nc_current_status.needsDbUpgrade
      fail_msg: "Nextcloud is not installed correctly"
      success_msg: "Nextcloud is installed"
  vars:
      nc_current_status: "{{ nc_status.stdout | from_json }}"

- name: Nextcloud | Post Install | Enable UFW port
  community.general.ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
  with_items:
      - "{{ cs_nc_port }}"

- name: Nextcloud | Post Install | Create log directory
  ansible.builtin.file:
      path: "{{ cs_nc_fail2ban_log_file | dirname }}"
      state: directory
      mode: "0755"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"

- name: Nextcloud | Post Install | Touch log file
  ansible.builtin.file:
      path: "{{ cs_nc_fail2ban_log_file }}"
      state: touch
      mode: "0777"
      owner: "{{ cs_nc_run_user }}"
      group: "{{ cs_nc_run_group }}"

- name: Nextcloud | Post Install | Add fail2ban filter
  ansible.builtin.copy:
      mode: "0644"
      dest: /etc/fail2ban/filter.d/100-nextcloud.conf
      src: files/nc/100-fail2ban-filter.conf

- name: Nextcloud | Post Install | Add fail2ban config
  ansible.builtin.template:
      mode: "0644"
      dest: /etc/fail2ban/jail.d/100-nextcloud.conf
      src: templates/nc/100-fail2ban.conf.j2

- name: Nextcloud | Post Install | Restart fail2ban
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
      state: restarted
  with_items:
      - fail2ban
      - sendmail

- name: Nextcloud | Post Install | Add missing indices
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ db:add-missing-indices"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true

- name: Nextcloud | Post Install | Disable admin user
  become: true
  become_user: "{{ cs_nc_run_user }}"
  ansible.builtin.command:
      cmd: "php occ user:disable {{ cs_nc_admin_user }}"
      chdir: "{{ cs_nc_web_dir }}"
  changed_when: true
