---
- name: Nextcloud | Users | Get all users
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ user:list --output=json"
      chdir: "{{ cs_nc_web_root_dir }}"
  register: cs_nc_user_list
  changed_when: false

- name: Nextcloud | Users | Create Admin User if not exists
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ user:add --password-from-env --group='admin' --display-name='nc-admin-{{ cs_nc_admin_user }}'
          --email='{{ cs_nc_mail_smtpname }}' '{{ cs_nc_admin_user }}'"
      chdir: "{{ cs_nc_web_root_dir }}"
  environment:
      OC_PASS: "{{ cs_nc_admin_password }}"
  changed_when: true
  when: "cs_nc_admin_user not in cs_nc_user_list.stdout | from_json"

- name: Nextcloud | Users | Get all users in admin group
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ group:list --output=json"
      chdir: "{{ cs_nc_web_root_dir }}"
  register: cs_nc_group_list
  changed_when: false

- name: Nextcloud | Users | Disable all admin users
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ user:disable {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  with_items: "{{ cs_nc_group_list.stdout | from_json | json_query('admin') }}"
  changed_when: true

- name: Nextcloud | Users | Set admin user properties
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  register: cs_nc_group_list
  changed_when: true
  with_items:
      - "user:setting {{ cs_nc_admin_user }} settings email {{ cs_nc_mail_smtpname }}"
      - "user:setting {{ cs_nc_admin_user }} core lang en"
      - "twofactorauth:disable {{ cs_nc_admin_user }} totp"
      - "user:enable {{ cs_nc_admin_user }}"

- name: Nextcloud | Users | Reset admin user password
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ {{ item }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  with_items:
      - "user:resetpassword {{ cs_nc_admin_user }} --password-from-env"
  environment:
      OC_PASS: "{{ cs_nc_admin_password }}"

- name: Nextcloud | Users | Get admin user info
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ user:info {{ cs_nc_admin_user }} --output=json"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: false
  register: cs_nc_admin_info

- name: Nextcloud | Users | Set admin user display_name
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ user:setting {{ cs_nc_admin_user }} settings display_name 'nc-admin-{{ cs_nc_admin_user }}'"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  when: "'nc-admin-'+cs_nc_admin_user != cs_nc_admin_info.stdout | from_json | json_query('display_name')"

- name: Nextcloud | Users | Add user to admin group
  become: true
  become_user: www-data
  ansible.builtin.command:
      cmd: "php occ group:adduser admin {{ cs_nc_admin_user }}"
      chdir: "{{ cs_nc_web_root_dir }}"
  changed_when: true
  when: "'admin' not in cs_nc_admin_info.stdout | from_json | json_query('groups')"
