---
cs_mini0_external_disk_enc_key_base64: "{{ vault_cred_cs_mini0_external_disk_enc_key_base64 }}"
cs_mini0_external_disk_enc_password: "{{ vault_cred_cs_mini0_external_disk_enc_password }}"
cs_mini0_external_disk_uuid: "{{ vault_cred_cs_mini0_external_disk_uuid }}"
cs_mini0_external_disk_crypt_open_name: mini0cryptdevice
cs_mini0_external_disk_mount_path: "/mnt/{{ cs_mini0_external_disk_crypt_open_name }}"

cs_mini0_working_dir: "{{ cs_mini0_external_disk_mount_path }}/app/minio"

cs_mini0_kes_group_name: kes
cs_mini0_kes_user_name: "{{ cs_mini0_kes_group_name }}"

cs_mini0_kes_working_dir: "{{ cs_mini0_working_dir }}/kes"
cs_mini0_kes_keystore_dir: "{{ cs_mini0_kes_working_dir }}/keystore"
cs_mini0_kes_config_file: "{{ cs_mini0_kes_working_dir }}/config.json"
cs_mini0_docker_network_name: mini0

cs_mini0_kes_cert_dir: "{{ cs_mini0_kes_working_dir }}/certs"
cs_mini0_kes_cert_file: "{{ cs_mini0_kes_cert_dir }}/cert.pem"
cs_mini0_kes_cert_key_file: "{{ cs_mini0_kes_cert_dir }}/cert-key.pem"
cs_mini0_kes_cert_id_file: "{{ cs_mini0_kes_cert_dir }}/cert-id"

cs_mini0_kes_container_name: kes
cs_mini0_kes_image: docker.io/minio/kes
cs_mini0_kes_version: 2024-10-31T07-42-41Z
cs_mini0_kes_port: 3000

cs_mini0_mini0_group_name: mini0
cs_mini0_mini0_user_name: "{{ cs_mini0_mini0_group_name }}"

cs_mini0_mini0_working_dir: "{{ cs_mini0_working_dir }}/mini0"
cs_mini0_mini0_data_dir: "{{ cs_mini0_mini0_working_dir }}/data"

cs_mini0_mini0_certs_dir: "{{ cs_mini0_mini0_working_dir }}/certs"

cs_mini0_mini0_private_key: "{{ cs_mini0_mini0_certs_dir }}/private.key"
cs_mini0_mini0_cert_file: "{{ cs_mini0_mini0_certs_dir }}/cert.pem"
cs_mini0_mini0_csr_file: "{{ cs_mini0_mini0_certs_dir }}/cert.csr"
cs_mini0_mini0_chain_file: "{{ cs_mini0_mini0_certs_dir }}/chain.pem"
cs_mini0_mini0_fullchain_file: "{{ cs_mini0_mini0_certs_dir }}/fullchain.pem"

cs_mini0_mini0_kes_cert_dir: "{{ cs_mini0_mini0_certs_dir }}/kes"
cs_mini0_mini0_kes_admin_cert: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-admin-cert.pem"
cs_mini0_mini0_kes_admin_key: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-admin-key.pem"
cs_mini0_mini0_kes_ca_cert: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-ca-cert.pem"

cs_mini0_mini0_kes_endpoint: https://{{ cs_mini0_kes_container_name }}:{{ cs_mini0_kes_port }}

cs_mini0_mini0_container_name: mini0
cs_mini0_mini0_image: docker.io/minio/minio
cs_mini0_mini0_version: RELEASE.2024-11-07T00-52-20Z
cs_mini0_mini0_default_kms_key_id: my-minio-key
cs_mini0_mini0_port: "{{ vault_cred_cs_mini0_mini0_port }}"
cs_mini0_mini0_console_port: "{{ vault_cred_cs_mini0_mini0_console_port }}"
cs_mini0_mini0_root_user: "{{ vault_cred_cs_mini0_mini0_root_user }}"
cs_mini0_mini0_root_password: "{{ vault_cred_cs_mini0_mini0_root_password }}"
cs_mini0_mini0_region: "{{ vault_cred_cs_mini0_mini0_region }}"
cs_mini0_mini0_domain: "{{ cs_public_ingress_dns_entry }}"
cs_mini0_mini0_private_ip: "{{ cs_rb4_m2_ip }}"
cs_mini0_mini0_public_ip: "{{ cs_public_ingress_ip }}"
