---
cs_mini0_working_dir: "{{ cs_mini0_external_disk_mount_path }}/minio"
# cs_mini0_working_dir: /app/minio

cs_mini0_mini0_group_name: mini0
cs_mini0_mini0_user_name: "{{ cs_mini0_mini0_group_name }}"

cs_mini0_mini0_working_dir: "{{ cs_mini0_working_dir }}/mini0"
cs_mini0_mini0_data_dir: "{{ cs_mini0_mini0_working_dir }}/data"

cs_mini0_mini0_certs_dir: "{{ cs_mini0_mini0_working_dir }}/certs"

cs_mini0_mini0_private_key: "{{ cs_mini0_mini0_certs_dir }}/private.key"
cs_mini0_mini0_cert_file: "{{ cs_mini0_mini0_certs_dir }}/public.crt"
minio_server_ca: "{{ cs_mini0_mini0_certs_dir }}/CAs/server-ca.crt"
cs_mini0_mini0_kes_cert_dir: "{{ cs_mini0_mini0_certs_dir }}/kes"
cs_mini0_mini0_kes_admin_cert: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-admin-cert.pem"
cs_mini0_mini0_kes_admin_key: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-admin-key.pem"
cs_mini0_mini0_kes_ca_cert: "{{ cs_mini0_mini0_kes_cert_dir }}/kes-ca-cert.pem"

cs_mini0_mini0_container_name: mini0
minio_cluster_name: mini0
cs_mini0_mini0_image: docker.io/minio/minio
cs_mini0_mini0_version: RELEASE.2024-11-07T00-52-20Z
cs_mini0_mini0_default_kms_key_id: my-minio-key

cs_mini0_mini0_domain: "{{ cs_public_ingress_dns_entry }}"

cs_mini0_mini0_public_ip: "{{ cs_public_ingress_ip }}"
minio_server_systemd_service_name: minio.service
minio_env_file: "{{ cs_mini0_mini0_working_dir }}/.env"

minio_server_bin_info_map:
    x86_64:
        minio_server_arch: amd64
        sha256sum:
            "RELEASE.2024-05-10T01-41-38Z": bd3a3e65c48d35613fe1c556e77a18bccb8aee911b6293ca5f6112f73376c105
            "RELEASE.2024-06-13T22-53-53Z": 1568c0d8ab09eebaf444f78ec9cd85ce62b1a2aacbd92ec29c1ec779864811bc
            "RELEASE.2024-11-07T00-52-20Z": c27873d791b56d33518de11f12c5bfae4be88ebac00e12c6dd0027b08123fd80
    aarch64:
        minio_server_arch: arm64
        sha256sum:
            "RELEASE.2024-05-10T01-41-38Z": b830c0862eadd2adb0db07118858fb917ac8002a9fde7a8eb0cc5234699ba40d
            "RELEASE.2024-06-13T22-53-53Z": e30af0de3db096a35d594e7e7fa501efd686cb3a3335f8576f36c7359ecde5a3
            "RELEASE.2024-11-07T00-52-20Z": 4c5ed5a8563b92a15c41a1cb9b382c448a72dc09026faecb4afb3eb44f10375b
