---
cs_nc_root_dir: /app/nextcloud
cs_nc_web_dir: "{{ cs_nc_root_dir }}/www"
cs_nc_data_dir: "{{ cs_nc_root_dir }}/data"
cs_nc_cert_dir: "{{ cs_nc_root_dir }}/certs"
cs_nc_root_ca_chain_pem_file: "{{ cs_nc_cert_dir }}/root_ca_chain.pem"

cs_nc_cert_privkey_file: "{{ cs_nc_cert_dir }}/privkey.pem"
cs_nc_cert_cert_file: "{{ cs_nc_cert_dir }}/cert.pem"
cs_nc_cert_cert_csr_file: "{{ cs_nc_cert_dir }}/cert.csr"
cs_nc_cert_chain_file: "{{ cs_nc_cert_dir }}/chain.pem"

cs_nc_apache_template_name: 100-nextcloud

cs_nc_db_cert_dir: "{{ cs_nc_cert_dir }}/db_certs"
cs_nc_db_cert_pem_file: "{{ cs_nc_db_cert_dir }}/db_cert.pem"
cs_nc_db_privkey_pem_file: "{{ cs_nc_db_cert_dir }}/db_privkey.pem"
cs_nc_db_chain_pem_file: "{{ cs_nc_db_cert_dir }}/db_chain.pem"
cs_nc_db_cert_csr_file: "{{ cs_nc_db_cert_dir }}/db_cert.csr"

cs_nc_cron_system_timer_name: nextcloud-cron

cs_nc_version: 29.0.4
cs_nc_run_user: www-data
cs_nc_run_group: www-data
cs_nc_log_file: "{{ cs_nc_data_dir }}/nextcloud.log"
cs_nc_logtimezone: Asia/Kolkata
cs_nc_default_phone_region: IN
cs_nc_fail2ban_log_file: "{{ cs_nc_data_dir }}/fail2ban.log"
cs_nc_php_version: 8.3
cs_nc_redis_timeout: 0.5

cs_nc_external_drive_mount_path: "{{ cs_nfs_external_drive_mount_path }}/nextcloud"
cs_nc_external_drive_mount_web_path: "{{ cs_nc_external_drive_mount_path }}/nextcloud"
cs_nc_external_drive_mount_data_dump_path: "{{ cs_nc_external_drive_mount_path }}/backup"
cs_nc_files_external_mount_folder_name: local_mnt_nextcloud_nextcloud
cs_nc_files_external_mount_group_name: local_mnt_nextcloud_nextcloud
cs_nc_files_scanner_systemd_timer_name: nextcloud-scanfiles

cs_nc_email_regex: (?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

cs_nc_domain: "{{ cs_public_ingress_dns_entry }}"
cs_nc_port: 8477

cs_nc_db_type: pgsql
cs_nc_db_user: "{{ cs_postgres_apps_dict.nextcloud.user }}"
cs_nc_db_password: "{{ cs_postgres_apps_dict.nextcloud.password }}"
cs_nc_db_database: "{{ cs_postgres_apps_dict.nextcloud.database }}"
cs_nc_db_host: "{{ cs_postgres_host_private_ip }}"
cs_nc_db_port: "{{ cs_postgres_port }}"

cs_nc_admin_user: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_admin_user') }}"
cs_nc_admin_password: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_admin_password') }}"

cs_nc_mail_smtpmode: "{{ cs_mail_smtpmode }}"
cs_nc_mail_sendmailmode: "{{ cs_mail_sendmailmode }}"
cs_nc_mail_smtpport: "{{ cs_mail_smtpport }}"
cs_nc_mail_from_address: "{{ cs_mail_from_address }}"
cs_nc_mail_domain: "{{ cs_mail_domain }}"
cs_nc_mail_smtpsecure: "{{ cs_mail_smtpsecure }}"
cs_nc_mail_smtpauth: "{{ cs_mail_smtpauth }}"
cs_nc_mail_smtphost: "{{ cs_mail_smtphost }}"
cs_nc_mail_smtpname: "{{ cs_mail_smtpname }}"
cs_nc_mail_smtppassword: "{{ cs_mail_smtppassword }}"

cs_nc_redis_cert_dir: "{{ cs_nc_cert_dir }}/redis"
cs_nc_redis_privkey_file: "{{ cs_nc_redis_cert_dir }}/redis.key"
cs_nc_redis_cert_file: "{{ cs_nc_redis_cert_dir }}/redis.crt"
cs_nc_redis_ca_file: "{{ cs_nc_redis_cert_dir }}/redis.ca"
cs_nc_redis_csr_file: "{{ cs_nc_redis_cert_dir }}/redis.csr"
cs_nc_redis_host: "{{ cs_redis_private_ip }}"
cs_nc_redis_port: "{{ cs_redis_tls_port }}"
cs_nc_redis_password: "{{ cs_redis_password }}"

cs_nc_imaginary_docker_container_name: imaginary
cs_nc_imaginary_docker_image: docker.io/nextcloud/aio-imaginary
cs_nc_imaginary_docker_image_tag: latest
cs_nc_imaginary_certs_dir: "{{ cs_nc_cert_dir }}/imaginary"
cs_nc_imaginary_privkey_file: "{{ cs_nc_imaginary_certs_dir }}/imaginary.key"
cs_nc_imaginary_cert_file: "{{ cs_nc_imaginary_certs_dir }}/imaginary.crt"
cs_nc_imaginary_csr_file: "{{ cs_nc_imaginary_certs_dir }}/imaginary.csr"
cs_nc_imaginary_fullchain_file: "{{ cs_nc_imaginary_certs_dir }}/imaginary.fullchain.pem"
cs_nc_imaginary_protocol: http
cs_nc_imaginary_key: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_imaginary_key') }}"
cs_nc_imaginary_port: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_imaginary_port') }}"
cs_nc_imaginary_domain: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_imaginary_domain') }}"

cs_nc_elasticsearch_password: "{{ cs_elasticsearch_password }}"
cs_nc_elasticsearch_servlet_port: "{{ cs_elasticsearch_servlet_port }}"
cs_nc_elasticsearch_host: "{{ cs_elasticsearch_host }}"
cs_nc_elasticsearch_index_name: nextcloud-fulltextsearch
cs_nc_elasticsearch_full_text_search_systemd_service_name: nextcloud-fulltext-elasticsearch-worker

cs_nc_onlyoffice_port: "{{ cs_onlyoffice_port }}"
cs_nc_onlyoffice_domain: "{{ cs_onlyoffice_domain }}"
cs_nc_onlyoffice_jwt_secret: "{{ cs_onlyoffice_jwt_secret }}"
cs_nc_users_dict: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nextcloud', 'custom_properties', 'cs_nc_users_dict') | from_json }}"

cs_nc_protocol: https

cs_nc_url: "{{ cs_nc_protocol }}://{{ cs_nc_domain }}:{{ cs_nc_port }}"
cs_nc_private_ip: "{{ cs_rb4_m3_ip }}"
