---
cs_nfs_client_ips:
    - "{{ cs_rb4_m1_ip }}"
    - "{{ cs_rb4_m2_ip }}"
cs_nfs_external_drive_luks_password: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nfs-server', 'custom_properties', 'cs_nfs_external_drive_luks_password') }}"
cs_nfs_external_drive_luks_key_file: "{{ lookup('viczem.keepass.keepass', 'home_inventory/nfs-server', 'attachments', 'cs_nfs_external_drive_luks_key_file') }}"
cs_nfs_external_drive_uuid: 0f5205e1-c864-4e33-87b5-0a69c91d86c4
cs_nfs_external_drive_mount_path: /mnt/nfsstorage
