---
- name: Database | MySQL | Install python3-mysqldb
  ansible.builtin.apt:
      name: python3-mysqldb

- name: Database | MySQL | Stop old containers
  community.docker.docker_container:
      name: "{{ item }}"
      state: absent
      force_kill: true
  with_items:
      - mysql-main

- name: Database | MySQL | Enable UFW port
  community.general.ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
  with_items:
      - "{{ cs_postgres_port }}"
      - "{{ cs_pg_admin_port }}"
