---
- name: Database | Redis | Create data directory
  ansible.builtin.file:
      path: "{{ cs_redis_data_dir }}"
      state: directory
      mode: "0755"

- name: Database | Redis | Stop old container
  community.docker.docker_container:
      name: redis-main
      state: absent
      force_kill: true

- name: Database | Redis | Enable UFW port
  community.general.ufw:
      rule: allow
      port: "{{ cs_redis_port }}"
      state: enabled

- name: Database | Redis | Start container
  community.docker.docker_container:
      name: redis-main
      image: docker.io/library/redis:7.2.0
      state: started
      restart_policy: unless-stopped
      volumes:
          - "{{ cs_redis_data_dir }}:/data"
      ports:
          - "{{ cs_redis_port }}:{{ cs_redis_port }}"
      command: redis-server --save 20 1 --loglevel warning
          --requirepass "{{ cs_redis_password }}"
          --port "{{ cs_redis_port }}"

- name: Database | Redis | Wait for service to start
  community.docker.docker_container_exec:
      container: redis-main
      command: redis-cli -a "{{ cs_redis_password }}" -p "{{ cs_redis_port }}" --no-auth-warning ping
  register: redis_ping
  retries: 30
  delay: 5
  until: redis_ping.stdout is defined and redis_ping.stdout == "PONG"
