---
- name: Jellyfin | Stop Jellyfin if running
  ansible.builtin.systemd_service:
      name: jellyfin
      state: stopped
      enabled: false
      daemon_reload: true
  register: __jellyfin_service_is_running
  failed_when: __jellyfin_service_is_running.failed and
      (
      __jellyfin_service_is_running.msg.find("Could not find the requested service") == -1
      )

- name: Jellyfin | Include common crypt mount
  ansible.builtin.include_tasks:
      file: tasks/common/crypt_mount.yml
  vars:
      cs_crypt_mount_vault_id: "{{ cs_jellyfin_external_disk_id }}"

- name: Jellyfin | Install packages
  ansible.builtin.apt:
      name:
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - python3-lxml
      state: present

- name: Jellyfin | Add Jellyfin gpg key
  ansible.builtin.apt_key:
      url: https://repo.jellyfin.org/debian/jellyfin_team.gpg.key
      state: present
      validate_certs: true
      keyring: /usr/share/keyrings/jellyfin-archive-keyring.gpg

- name: Jellyfin | Gather facts
  ansible.builtin.setup:
      gather_subset: all

- name: Jellyfin | Add Jellyfin repository
  ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/jellyfin-archive-keyring.gpg
          arch={{ cs_jellyfin_ansible_arch_map[ansible_architecture] }}]
          https://repo.jellyfin.org/debian {{ ansible_distribution_release }} main"
      state: present
      validate_certs: true
      update_cache: true
      filename: jellyfin.list

- name: Jellyfin | Install Jellyfin
  ansible.builtin.apt:
      name: jellyfin
      state: present
      update_cache: true

- name: Jellyfin | Check if /etc/jellyfin/network.xml exists
  ansible.builtin.stat:
      path: /etc/jellyfin/network.xml
  register: __jellyfin_network_xml_exists

- name: Jellyfin | Fail if /etc/jellyfin/network.xml does not exist
  no_log: false
  ansible.builtin.fail:
      msg: "Jellyfin network.xml does not exist,
          Do the initial setup manually and re-run the playbook."
  when: not __jellyfin_network_xml_exists.stat.exists

- name: Jellyfin | Get Public Ingress IP and Hostname from vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_kv2_get:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      engine_mount_point: "secret"
      path: "blr-home-lab"
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
  register: __jellyfin_server_public_ingress_secret_dict
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Jellyfin | Set fact Public Ingress IP and Hostname
  ansible.builtin.set_fact:
      cs_public_ingress_ip: "{{ __jellyfin_server_public_ingress_secret_dict.secret.public_ingress_ip }}"
      cs_public_ingress_dns_entry: "{{ __jellyfin_server_public_ingress_secret_dict.secret.public_ingress_dns_entry }}"

- name: Jellyfin | Get Server Certificates from Vault
  become: false
  delegate_facts: true
  delegate_to: localhost
  community.hashi_vault.vault_write:
      url: "https://{{ vault_ha_client.vault_ha_hostname }}:{{ vault_ha_client.vault_ha_port }}"
      path: pki/issue/server_certificate
      token: "{{ vault_ha_client.token }}"
      validate_certs: true
      data:
          common_name: "{{ cs_public_ingress_dns_entry }}"
          alt_names: "{{ cs_public_ingress_dns_entry }},localhost,{{ ansible_fqdn }}"
          # Because in the inv plugin ansible host hast to be a ip
          ip_sans: "127.0.0.1,{{ ansible_host }},{{ cs_public_ingress_ip }}"
  register: __jellyfin_server_cert
  environment:
      VAULT_CACERT: "{{ vault_ha_client.vault_root_ca_cert_file }}"
      VAULT_CLIENT_CERT: "{{ vault_ha_client.vault_client_cert_file }}"
      VAULT_CLIENT_KEY: "{{ vault_ha_client.vault_client_key_file }}"

- name: Jellyfin | Create temp files
  ansible.builtin.tempfile:
      state: file
      suffix: ".pem"
  with_items:
      - cert
      - chain
      - issuing_ca
      - key
  register: __jellyfin_temp_files

- name: Jellyfin | Create cert dir
  ansible.builtin.file:
      path: /etc/jellyfin/cert
      state: directory
      owner: jellyfin
      group: jellyfin
      mode: "0777"

- name: Jellyfin | Write Server Certificate
  ansible.builtin.copy:
      content: "{{ item.content }}"
      dest: "{{ item.dest }}"
      mode: "0644"
  loop:
      - content: "{{ __jellyfin_server_cert.data.data.certificate }}\n\
            {{ __jellyfin_server_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ __jellyfin_temp_files.results[0].path }}"
      - content: "{{ __jellyfin_server_cert.data.data.ca_chain | join('\n') }}"
        dest: "{{ __jellyfin_temp_files.results[1].path }}"
      - content: "{{ __jellyfin_server_cert.data.data.issuing_ca }}"
        dest: "{{ __jellyfin_temp_files.results[2].path }}"
      - content: "{{ __jellyfin_server_cert.data.data.private_key }}"
        dest: "{{ __jellyfin_temp_files.results[3].path }}"

- name: Jellyfin | Set random password
  ansible.builtin.set_fact:
      cs_jellyfin_p12_cert_password: "{{ lookup('ansible.builtin.password', '/dev/null', length=40,
          chars=['ascii_letters', 'digits']) }}"

- name: Jellyfin | Generate PKCS#12 file
  changed_when: true
  become: true
  become_user: root
  ansible.builtin.shell:
      cmd: |+
          openssl pkcs12 -export -out /etc/jellyfin/cert/jellyfin.pfx \
          -inkey {{ __jellyfin_temp_files.results[3].path }} \
          -in "{{ __jellyfin_temp_files.results[0].path }}" \
          -certfile "{{ __jellyfin_temp_files.results[2].path }}" \
          -password "pass:{{ cs_jellyfin_p12_cert_password }}"

          chmod 0444 /etc/jellyfin/cert/jellyfin.pfx
          chown jellyfin:jellyfin /etc/jellyfin/cert/jellyfin.pfx

# - name: Jellyfin | Generate PKCS#12 file
#   community.crypto.openssl_pkcs12:
#       action: export
#       path: /etc/jellyfin/cert/jellyfin.pfx
#       mode: "0444"
#       owner: jellyfin
#       group: jellyfin
#       friendly_name: raclette
#       encryption_level: auto
#       privatekey_content: "{{ __jellyfin_server_cert.data.data.private_key }}"
#       certificate_path: "{{ __jellyfin_temp_files.results[0].path }}"
#       other_certificates_parse_all: false
#       passphrase: "{{ cs_jellyfin_p12_cert_password }}"
#       other_certificates:
#           - "{{ __jellyfin_temp_files.results[2].path }}"
#           - "{{ __jellyfin_temp_files.results[1].path }}"
#           - "{{ __jellyfin_temp_files.results[0].path }}"
#       state: present

- name: Jellyfin | Configure Network Ports
  when: __jellyfin_network_xml_exists.stat.exists
  community.general.xml:
      path: /etc/jellyfin/network.xml
      xpath: /NetworkConfiguration/{{ item.xpath }}
      value: "{{ item.value }}"
  with_items:
      - xpath: "PublicHttpPort"
        value: "{{ cs_jellyfin_public_http_port }}"
      - xpath: "PublicHttpsPort"
        value: "{{ cs_jellyfin_public_https_port }}"
      - xpath: "InternalHttpPort"
        value: "{{ cs_jellyfin_internal_http_port }}"
      - xpath: "InternalHttpsPort"
        value: "{{ cs_jellyfin_internal_https_port }}"
      - xpath: "EnableRemoteAccess"
        value: "true"
      - xpath: "EnableHttps"
        value: "true"
      - xpath: "RequireHttps"
        value: "false"
      - xpath: "CertificatePath"
        value: "/etc/jellyfin/cert/jellyfin.pfx"
      - xpath: "CertificatePassword"
        value: "{{ cs_jellyfin_p12_cert_password }}"
      - xpath: "AutoDiscovery"
        value: "true"
      - xpath: "EnableUPnP"
        value: "true"
      - xpath: "EnableIPv4"
        value: "true"
      - xpath: "EnableIPv6"
        value: "false"
      - xpath: "EnableRemoteAccess"
        value: "true"
      - xpath: "IgnoreVirtualInterfaces"
        value: "true"

- name: Jellyfin | Enable UFW Firewall
  when: false # TODO: Uncomment when ready
  community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: tcp
      state: enabled
      comment: "Allow Jellyfin {{ item.comment }}, Managed by Ansible home-lab playbook."
  with_items:
      - port: "{{ cs_jellyfin_internal_http_port }}"
        comment: "Internal HTTP Port"
      - port: "{{ cs_jellyfin_internal_https_port }}"
        comment: "Internal HTTPS Port"
      - port: "{{ cs_jellyfin_public_http_port }}"
        comment: "Public HTTP Port"
      - port: "{{ cs_jellyfin_public_https_port }}"
        comment: "Public HTTPS Port"

- name: Jellyfin | Enable UFW UDP Firewall
  community.general.ufw:
      rule: allow
      port: "{{ item.port }}"
      proto: udp
      state: enabled
      comment: "Allow Jellyfin {{ item.comment }} port, Managed by Ansible home-lab playbook."
  with_items:
      - port: 1900
        comment: "service auto-discovery"
      - port: 7359
        comment: "auto-discovery"

- name: Jellyfin | Add jellyfin to video group
  ansible.builtin.user:
      name: jellyfin
      groups: video
      append: true
      state: present

- name: Jellyfin | Data directory
  ansible.builtin.file:
      path: "{{ cs_jellyfin_data_dir }}"
      state: directory
      owner: jellyfin
      group: jellyfin
      recurse: true
      mode: "0777"

- name: Jellyfin | Start Jellyfin
  ansible.builtin.systemd_service:
      name: jellyfin
      state: restarted
      enabled: true
      daemon_reload: true
