---
- name: Mini0 | Add to inv | Get Instance Info
  linode.cloud.instance_info:
      label: "{{ pv_cs_minio_linode_instance_label }}"
      api_token: "{{ pv_cs_linode_api_token }}"
  register: minio_linode_instance_info

- name: Mini0 | Add to inv | Wait for the instance to be ready
  ansible.builtin.wait_for:
      host: "{{ minio_linode_instance_info.networking.ipv4.public[0].rdns }}"
      port: 22
      delay: 10
      timeout: 300
      state: started

- name: Mini0 | Add to inv | Define a temp file for ssh key
  ansible.builtin.tempfile:
      state: file
  register: ssh_key_file_temp

- name: Mini0 | Add to inv | Write the ssh key to the temp file
  ansible.builtin.copy:
      content: "{{ pv_cs_linode_ssh_key_priv_base64 | ansible.builtin.b64decode }}"
      dest: "{{ ssh_key_file_temp.path }}"
      mode: "0600"

- name: Mini0 | Add to inv | Add the instance to the inventory group with root user
  ansible.builtin.add_host:
      hostname: cs-minio-linode-host
      ansible_ssh_host: "{{ minio_linode_instance_info.networking.ipv4.public[0].address }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_user: root
      ansible_connection: ssh
      ansible_ssh_private_key_file: "{{ ssh_key_file_temp.path }}"

- name: Mini0 | Add to inv | Try to connect to the instance with root user
  delegate_to: cs-minio-linode-host
  ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 3
  register: wait_for_connection_with_root
  ignore_errors: true

- name: Mini0 | Add to inv | Add the instance to the inventory group with service user
  ansible.builtin.add_host:
      hostname: cs-minio-linode-host
      ansible_ssh_host: "{{ minio_linode_instance_info.networking.ipv4.public[0].address }}"
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      ansible_user: "{{ cs_vm_ssh_service_user_id }}"
      ansible_connection: ssh
      ansible_become_method: sudo
      ansible_ssh_private_key_file: "{{ ssh_key_file_temp.path }}"
  when: wait_for_connection_with_root.failed

- name: Mini0 | Add to inv | Try to connect to the instance with service user
  delegate_to: cs-minio-linode-host
  ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 3
  when: wait_for_connection_with_root.failed
