---
- name: Mini0 | Linode | Create Volume
  linode.cloud.volume:
      label: "{{ minio_sdic_linode_volume_label }}"
      region: "{{ sdic_linode_region }}"
      size: 10
      api_token: "{{ linode_api_token }}"
      state: present
  register: sdic_minio_volume_create

- name: Mini0 | Linode | Create Mini0 Instance
  linode.cloud.instance:
      api_token: "{{ linode_api_token }}"
      label: "{{ minio_sdic_linode_instance_label }}"
      region: "{{ sdic_linode_region }}"
      type: g6-nanode-1
      booted: true
      boot_config_label: sdic-minio-boot-config
      state: present
      rebooted: false
      private_ip: false
      wait: true
      wait_timeout: 1500
      tags:
          - sdic
          - minio
          - sdic-minio
          - env=production
      disks:
          - label: boot
            size: 25088
            image: linode/debian12
            authorized_keys:
                - "{{ sdic_linode_id_ed25519_pub }}"
          - label: swap
            filesystem: swap
            size: 512
      configs:
          - label: sdic-minio-boot-config
            root_device: /dev/sda
            kernel: "linode/grub2"
            devices:
                sda:
                    disk_label: boot
                sdb:
                    disk_label: swap
                sdc:
                    volume_id: "{{ sdic_minio_volume_create.volume.id }}"
  register: sdic_minio_instance_create

- name: Mini0 | Linode | Debug | Show the instance info
  ansible.builtin.debug:
      var: sdic_minio_instance_create

- name: Mini0 | Linode | Set Public IPv4 and IPv6
  ansible.builtin.set_fact:
      sdic_minio_instance_public_ipv4: "{{ sdic_minio_instance_create.networking.ipv4.public[0].address }}"

- name: Mini0 | Linode | Set A Record for Mini0
  linode.cloud.domain_record:
      domain: "{{ sdic_linode_manage_domain }}"
      name: "{{ minio_server_sub_domain_name }}"
      type: "A"
      target: "{{ sdic_minio_instance_public_ipv4 }}"
      state: present
      ttl_sec: 300
      api_token: "{{ linode_api_token }}"

- name: Mini0 | Linode | Update reverse DNS
  linode.cloud.ip_rdns:
      state: present
      address: "{{ sdic_minio_instance_public_ipv4 }}"
      rdns: "{{ minio_server_domain }}"
      api_token: "{{ linode_api_token }}"
