---
- name: Mini0 | KES | Create Group
  become: true
  become_user: root
  ansible.builtin.group:
      name: "{{ pv_cs_minio_kes_group_name }}"
      state: present
      system: true
  register: minio_kes_group_name_create

- name: Mini0 | KES | Create User
  become: true
  become_user: root
  ansible.builtin.user:
      name: "{{ pv_cs_minio_kes_user_name }}"
      group: "{{ pv_cs_minio_kes_group_name }}"
      groups:
          - docker
      shell: /bin/false
      system: true
      state: present
  register: minio_kes_user_name_create

- name: Mini0 | KES | Create Directory
  become: true
  become_user: root
  ansible.builtin.file:
      name: "{{ item }}"
      owner: "{{ pv_cs_minio_kes_user_name }}"
      group: "{{ pv_cs_minio_kes_group_name }}"
      mode: "0755"
      state: directory
  with_items:
      - "{{ pv_cs_minio_kes_working_dir }}"
      - "{{ pv_cs_minio_kes_keystore_dir }}"

- name: Mini0 | KES | Docker Network
  become: true
  become_user: root
  community.docker.docker_network:
      name: "{{ pv_cs_minio_docker_network_name }}"
      state: present

- name: Mini0 | KES | Touch Cert Files
  become: true
  become_user: root
  ansible.builtin.file:
      path: "{{ item }}"
      state: touch
      mode: "0644"
      owner: "{{ pv_cs_minio_kes_user_name }}"
      group: "{{ pv_cs_minio_kes_group_name }}"
  with_items:
      - "{{ pv_cs_minio_kes_cert_file }}"
      - "{{ pv_cs_minio_kes_cert_key_file }}"
      - "{{ pv_cs_minio_kes_cert_id_file }}"

- name: Mini0 | KES | Remove old Container
  become: true
  become_user: root
  community.docker.docker_container:
      name: "{{ pv_cs_minio_kes_container_name }}"
      state: absent
      force_kill: true

- name: Mini0 | KES | Create Certificates
  become: true
  become_user: "{{ pv_cs_minio_kes_user_name }}"
  community.docker.docker_container:
      name: "{{ pv_cs_minio_kes_container_name }}"
      image: "{{ pv_cs_minio_kes_image }}:{{ pv_cs_minio_kes_version }}"
      user: "{{ minio_kes_user_name_create.uid }}:{{ minio_kes_group_name_create.gid }}"
      auto_remove: true
      entrypoint: ""
      working_dir: /
      volumes:
          - "{{ pv_cs_minio_kes_cert_file }}:{{ pv_cs_minio_kes_cert_file }}"
          - "{{ pv_cs_minio_kes_cert_key_file }}:{{ pv_cs_minio_kes_cert_key_file }}"
          - "{{ pv_cs_minio_kes_cert_id_file }}:{{ pv_cs_minio_kes_cert_id_file }}"
      command:
          - "/bin/bash"
          - "-c"
          - "/kes identity new --key '{{ pv_cs_minio_kes_cert_key_file }}' --cert '{{ pv_cs_minio_kes_cert_file }}' \
            kesadmin --force --dns '{{ pv_cs_minio_kes_container_name }}' && \
            /kes identity of '{{ pv_cs_minio_kes_cert_file }}' | tee '{{ pv_cs_minio_kes_cert_id_file }}'"

- name: Mini0 | KES | Read Certificate ID
  become: true
  become_user: root
  ansible.builtin.slurp:
      src: "{{ pv_cs_minio_kes_cert_id_file }}"
  register: minio_kes_cert_id_file_read

- name: Mini0 | KES | Set Config Fact
  ansible.builtin.set_fact:
      minio_kes_config:
          version: v1
          address: 0.0.0.0:{{ pv_cs_minio_kes_port }}
          admin:
              identity: "{{ minio_kes_cert_id_file_read.content | b64decode }}"
          tls:
              key: "{{ pv_cs_minio_kes_cert_key_file }}"
              cert: "{{ pv_cs_minio_kes_cert_file }}"
              auth: "on"
              ca: "{{ pv_cs_minio_kes_cert_file }}"
          policy:
              minio:
                  allow:
                      - /v1/key/create/*
                      - /v1/key/generate/*
                      - /v1/key/decrypt/*
                      - /v1/key/bulk/decrypt
                      - /v1/key/list/*
                      - /v1/status
                      - /v1/metrics
                      - /v1/log/audit
                      - /v1/log/error

          keystore:
              fs:
                  path: "{{ pv_cs_minio_kes_keystore_dir }}"
          log:
              error: "on"
              audit: "on"

- name: Mini0 | KES | Write Config
  become: true
  become_user: root
  ansible.builtin.copy:
      content: "{{ minio_kes_config | to_nice_yaml }}"
      dest: "{{ pv_cs_minio_kes_config_file }}"
      owner: "{{ pv_cs_minio_kes_user_name }}"
      group: "{{ pv_cs_minio_kes_group_name }}"
      mode: "0644"

- name: Mini0 | KES | Start Container
  become: true
  become_user: "{{ pv_cs_minio_kes_user_name }}"
  community.docker.docker_container:
      name: "{{ pv_cs_minio_kes_container_name }}"
      image: "{{ pv_cs_minio_kes_image }}:{{ pv_cs_minio_kes_version }}"
      user: "{{ minio_kes_user_name_create.uid }}:{{ minio_kes_group_name_create.gid }}"
      auto_remove: false
      detach: true
      restart_policy: unless-stopped
      hostname: "{{ pv_cs_minio_kes_container_name }}"
      networks:
          - name: "{{ pv_cs_minio_docker_network_name }}"
      volumes:
          - "{{ pv_cs_minio_kes_working_dir }}:{{ pv_cs_minio_kes_working_dir }}"
      command:
          - server
          - --config={{ pv_cs_minio_kes_config_file }}
