---
- name: Mini0 | Linode
  ansible.builtin.import_tasks:
      file: tasks/minio/create_linode.yml

- name: Mini0 | Add to inv
  ansible.builtin.import_tasks:
      file: tasks/minio/add_inv.yml

- name: Mini0 | Patch Cloud System
  delegate_to: sdic-minio-linode-host
  ansible.builtin.import_tasks: tasks/patch_system.yml

- name: Mini0 | Reboot Mini0 Instance
  block:
      - name: Mini0 | Reboot Mini0 Instance | Reboot
        linode.cloud.instance:
            api_token: "{{ sdic_linode_api_token }}"
            label: "{{ minio_sdic_linode_instance_label }}"
            state: present
            rebooted: true

      - name: Mini0 | Reboot Mini0 Instance | Wait
        delegate_to: sdic-minio-linode-host
        ansible.builtin.wait_for_connection:
            delay: 1
            timeout: 1
        retries: 30
        delay: 3

- name: Mini0 | Disk
  delegate_to: sdic-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/disk.yml

- name: Mini0 | KES
  delegate_to: sdic-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/kes.yml

- name: Mini0 | Mini0
  delegate_to: sdic-minio-linode-host
  ansible.builtin.import_tasks:
      file: tasks/minio/minio.yml
