---
- name: Mini0 | Patch Cloud System | Linux Patching
  become: true
  ansible.builtin.import_role:
      name: arpanrec.nebula.linux_patching
  vars:
      linux_patching_rv_install_devel_packages: false

- name: Mini0 | Patch Cloud System | Make sure zsh is installed
  become: true
  ansible.builtin.apt:
      name: zsh
      state: present
      update_cache: true

- name: Mini0 | Patch Cloud System | Add application user
  become: true
  ansible.builtin.import_role:
      name: arpanrec.nebula.user_add
  vars:
      user_add_rv_username: "{{ linode_vm_ssh_service_user }}"
      user_add_rv_ssh_access_public_key_content_list:
          - "{{ linode_ssh_key_pub }}"
      user_add_rv_user_default_shell: "/bin/zsh"
      user_add_rv_user_nopasswd_commands: ["ALL"]
      user_add_rv_user_extra_groups: ["wheel"]

- name: Mini0 | Patch Cloud System | SSH Hardening
  become: true
  ansible.builtin.import_role:
      name: arpanrec.nebula.ssh_hardening

- name: Mini0 | Patch Cloud System | Install Docker
  become: true
  ansible.builtin.import_role:
      name: geerlingguy.docker
  vars:
      docker_users:
          - "{{ linode_vm_ssh_service_user }}"

- name: Mini0 | Patch Cloud System | Flush Handlers after root tasks
  become: true
  ansible.builtin.meta: flush_handlers

- name: Mini0 | Patch Cloud System | Beautify Terminal
  become: true
  become_user: "{{ linode_vm_ssh_service_user }}"
  ansible.builtin.import_role:
      name: arpanrec.nebula.terminal

- name: Mini0 | Patch Cloud System | Flush Handlers after user tasks
  become: true
  become_user: "{{ linode_vm_ssh_service_user }}"
  ansible.builtin.meta: flush_handlers
