---
cs_postgres_container_name: postgres
cs_postgres_network_name: postgres

cs_postgres_run_user: "999"
cs_postgres_run_group: "999"

cs_postgres_data_dir: "{{ cs_postgres_dir }}/data"
cs_postgres_certs_dir: "{{ cs_postgres_dir }}/certs"
cs_postgres_certs_privkey_file: "{{ cs_postgres_certs_dir }}/privkey.pem"
cs_postgres_certs_cert_file: "{{ cs_postgres_certs_dir }}/cert.pem"
cs_postgres_certs_chain_file: "{{ cs_postgres_certs_dir }}/chain.pem"
cs_postgres_hba_file: "{{ cs_postgres_dir }}/pg_hba.conf"
cs_postgres_client_certs_dir: "{{ cs_postgres_dir }}/client_certs"
cs_postgres_cluster_name: "{{ cs_postgres_container_name }}"
cs_postgres_version: "16.5"
cs_postgres_docker_image: docker.io/library/postgres
cs_postgres_docker_image_tag: "{{ cs_postgres_version }}-bookworm"

cs_postgres_port: "{{ vault_cred_cs_postgres_port }}"
cs_postgres_maintenance_db: "{{ vault_cred_cs_postgres_maintenance_db }}"

cs_postgres_apps_dict: "{{ vault_cred_cs_postgres_apps_dict }}"

cs_postgres_pg_admin_run_user: "5050"
cs_postgres_pg_admin_run_group: "5050"

cs_postgres_pg_admin_dir: "{{ cs_postgres_dir }}/pgadmin"
cs_postgres_pg_admin_certs_dir: "{{ cs_postgres_pg_admin_dir }}/certs"
cs_postgres_pg_admin_certs_privkey_file: "{{ cs_postgres_pg_admin_certs_dir }}/privkey.pem"
cs_postgres_pg_admin_certs_cert_file: "{{ cs_postgres_pg_admin_certs_dir }}/cert.pem"
cs_postgres_pg_admin_certs_chain_file: "{{ cs_postgres_pg_admin_certs_dir }}/chain.pem"
cs_postgres_pg_admin_certs_fullchain_file: "{{ cs_postgres_pg_admin_certs_dir }}/fullchain.pem"
cs_postgres_pg_admin_certs_csr_file: "{{ cs_postgres_pg_admin_certs_dir }}/csr.pem"
cs_postgres_pg_admin_client_certs_dir: "{{ cs_postgres_pg_admin_dir }}/client_certs"
ps_postgres_pg_admin_pg_pass_file: "{{ cs_postgres_pg_admin_dir }}/pgpass"
ps_postgres_pg_admin_pg_servers_file: "{{ cs_postgres_pg_admin_dir }}/pg_servers.json"
ps_postgres_pg_admin_entrypoint_file: "{{ cs_postgres_pg_admin_dir }}/entrypoint.sh"

ps_postgres_pg_admin_docker_container_name: pgadmin
ps_postgres_pg_admin_docker_image: docker.io/dpage/pgadmin4
ps_postgres_pg_admin_docker_image_tag: 8.13.0

cs_postgres_pg_admin_domain: "{{ cs_public_ingress_dns_entry }}"
cs_postgres_pg_admin_email: "{{ cs_mail_smtpname }}"
cs_postgres_pg_admin_password: "{{ vault_cred_cs_postgres_pg_admin_password }}"
cs_postgres_pg_admin_port: "{{ vault_cred_cs_postgres_pg_admin_port }}"
